// packages/vue-infinitegrid/demo/layouts/GridLayout.vue
<template>
    <GridLayout
		ref="ig"
        :options="{
            align: 'center',
            transitionDuration: 0.2,
            isOverflowScroll: false,
        }"
        @append="onAppend"
        @layout-complete="onLayoutComplete"
        @image-error="onImageError"
    >
        <Loading><div>Loading</div></Loading>
        <div class="item" v-for="(item, i) in list" :key="item.key"
            @click="remove(i)">
            <div class="thumbnail">
                <img :src="`https://naver.github.io/egjs-infinitegrid/assets/image/${(item.num + 1) % 59}.jpg`"/>
            </div>
            <div class="info">
                egjs {{ item.num }}
            </div>
        </div>
    </GridLayout>
</template>
<script>
export default {
    data() {
        return {
            start: 0,
            loading: false,
            list: [],
        };
	}, 
    methods: {
        loadItems(groupKey, num) {
            const items = [];
            const start = this.start || 0;

            for (let i = 0; i < num; ++i) {
                items.push({
                    groupKey,
                    num: start + i,
                    key: start + i
                });
            }
            this.start = start + num;
            return items;
        },
        remove(index) {
            this.list.splice(index, 1);
        },
        onAppend({ groupKey }) {
            const list = this.list;
            const items = this.loadItems(parseFloat(groupKey || 0) + 1, 5);
			window.a = this.$refs.ig;

			this.$refs.ig.startLoading();
			console.log("start")
			this.list = list.concat(items);
        },
        onLayoutComplete({ isLayout }) {
			console.log("complete")
            if (!isLayout) {
                this.$refs.ig.endLoading();
            }
        },
        onImageError({ totalIndex }) {
            this.list.splice(totalIndex, 1);
        }
    }
}
</script>
<style scoped>
.item {
	width: 250px;
	opacity: 1;
}
.item .thumbnail {
	max-height: 300px;
	overflow: hidden;
	border-radius: 8px;
}
.item .thumbnail img {
	width: 100%;
}
.item .info {
	margin-top: 10px;
	font-weight: bold;
	color: #777;
}
.item.animate {
	transition: opacity ease 1s;
	transition-delay: 0.2s;
	opacity: 1;
}
.loading {
	position: absolute;
	width: 100%;
	height: 50px;
	line-height: 50px;
	text-align: center;
	font-weight: bold;
}
</style>

// packages/react-infinitegrid/examples/js/GridLayout.js
import React, {Component} from "react";
import ReactDOM from "react-dom";
import {GridLayout, JustifiedLayout} from "../../src/index";


class Item extends Component {
	render() {
		const no = this.props.num;
		const text = `egjs ${no}`;

		return (<div className="item" onClick={this.props.onClick}>
			<div className="thumbnail">
				<img src={`https://naver.github.io/egjs-infinitegrid/assets/image/${no % 59 + 1}.jpg`}/>
			</div>
			<div className="info">
				{text}
			</div>
		</div>);
	}
}

class App extends Component {
	constructor(prop) {
		super(prop);
		this.loading = (<div className="loading">Loading...</div>);
		this.start = 0;
		this.state = {
			loading: null,
			list: [],
		};
	}
	loadItems(groupKey, num) {
		const items = [];
		const start = this.start || 0;

		for (let i = 0; i < num; ++i) {
			items.push(<Item groupKey={groupKey} num={1 + start + i} key={start + i}
				onClick={(itemKey => (e => this.remove(itemKey)))(start + i)}/>);
		}
		this.start = start + num;
		return items;
	}
	remove(itemKey) {
		const list = this.state.list.slice();
		const index = list.map(component => parseFloat(component.key)).indexOf(itemKey);

		// console.log(itemKey, index);
		list.splice(index, 1);
		this.setState({list});
	}
	onAppend = ({groupKey}) => {
		const list = this.state.list;
		const items = this.loadItems(parseFloat(groupKey) + 1, 5);

		this.setState({loading: true, list: list.concat(items)});
	}
	onLayoutComplete = ({isLayout}) => {
		window.b = this;
		!isLayout && this.setState({loading: false});
	}
	render() {
		const {list} = this.state;

		return (
			<GridLayout margin={10}
				align={"center"}
				onAppend={this.onAppend}
				onLayoutComplete={this.onLayoutComplete}
				loading = {this.state.loading}
				ref = {e => {window.e = e;}}
			>
				{list}
			</GridLayout>
		);
	}
}

ReactDOM.render(<App />, document.getElementById("__react-content"));
