// packages/react-infinitegrid/src/demo/App.tsx
import React from 'react';
import './App.css';
import { GridLayout } from '../react-infinitegrid';

class Item extends React.Component<{
  groupKey: any,
  num: number,
  onClick: any,
}> {
  render() {
    const no = this.props.num;
    const text = `egjs ${no}`;

    return (<div className="item" onClick={this.props.onClick}>
      <div className="thumbnail">
        <img src={`https://naver.github.io/egjs-infinitegrid/assets/image/${no % 59}.jpg`} />
      </div>
      <div className="info">
        {text}
      </div>
    </div>);
  }
}

class App extends React.Component<{}, {
  list: any[],
}> {
  public start = 0;
  constructor(prop) {
    super(prop);
    this.state = {
      list: [
        // ...this.loadItems("1", 10),
        // ...this.loadItems("2", 10),
      ],
    };
  }
  loadItems(groupKey, num) {
    const items = [];
    const start = this.start || 0;

    for (let i = 0; i < num; ++i) {
      items.push(<Item groupKey={groupKey} num={start + i} key={start + i}
        onClick={(itemKey => (e => this.remove(itemKey)))(start + i)} />);
    }
    this.start += num;
    return items;
  }
  remove(itemKey) {
    const list = this.state.list.slice();
    const index = list.map(component => parseFloat(component.key)).indexOf(itemKey);

    list.splice(index, 1);
    this.setState({ list });
  }
  onAppend = ({ currentTarget, groupKey, startLoading }) => {
    if (currentTarget.isLoading()) {
      return;
    }
    startLoading();
    const list = this.state.list;
    const items = this.loadItems(parseFloat(groupKey || 0) + 1, 5);

    this.setState({ list: list.concat(items) });
  }
  onLayoutComplete = ({ isAppend, isLayout, endLoading, fromCache }) => {
    !isLayout && endLoading();
  }
  onImageError = ({ totalIndex }) => {
    this.state.list.splice(totalIndex, 1);
    this.setState({ list: this.state.list });
  }
  render() {
    const { list } = this.state;

    return (
      <GridLayout
        ref={e => {
          (window as any).a = e;
        }}
        options = {{
          transitionDuration: 0,
          isConstantSize: false,
        }}
        layoutOptions={{
          margin: 10,
          align: "center",
        }}
        onAppend={this.onAppend}
        onLayoutComplete={this.onLayoutComplete}
        onImageError={this.onImageError}
        useFirstRender={true}
        loading={<div className="loading" style={{textAlign: "center", height: "100px", backgroundColor: "#f55", position: "absolute"}}>LOADING</div>}
        // status={status}
      >
        {list}
      </GridLayout>
    );
  }
}


export default App;

// packages/ngx-infinitegrid/src/app/app.component.ts
import { Component, ViewChild } from '@angular/core';
import { NgxInfinitegridComponent } from 'projects/ngx-infinitegrid/src/public-api';
import { IItem } from '@egjs/infinitegrid';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  @ViewChild('ig', { static: false }) ig: NgxInfinitegridComponent;
  visibleItems = [];
  title = 'ngx-infinitegrid-app';
  start = 7;
  items = [
    {
      groupKey: 0,
      itemKey: 1,
      no: 0,
    },
    {
      groupKey: 0,
      itemKey: 2,
      no: 1,
    },
    {
      groupKey: 0,
      itemKey: 3,
      no: 2,
    },
    {
      groupKey: 1,
      itemKey: 4,
      no: 3,
    },
    {
      groupKey: 1,
      itemKey: 5,
      no: 4,
    },
    {
      groupKey: 1,
      itemKey: 6,
      no: 5,
    },
  ];
  loadItems(groupKey: number, num: number) {
    const items = this.items;
    const start = this.start || 0;

    for (let i = 0; i < num; ++i) {
      items.push({
        groupKey,
        itemKey: start + i,
        no: start + i,
      });
    }
    this.items = [...items];
    this.start += num;
  }
  onAppend({ currentTarget, groupKey, startLoading }) {
    (window as any).a = this;
    if (currentTarget.isLoading()) {
      return;
    }
    startLoading();
    this.loadItems(parseFloat(groupKey || 0) + 1, 5);
  }
  onLayoutComplete({ isAppend, isLayout, endLoading, fromCache }) {
    if (!isLayout) {
      endLoading();
    }
  }
  onImageError({ totalIndex }) {
    this.items.splice(totalIndex, 1);
    this.items = [ ...this.items ];
  }
  trackBy(index: number, item: IItem): any {
    return item.itemKey;
  }
}

<!--The content below is only a placeholder and can be replaced.-->
<div style="text-align:center">
  <h1>
    Welcome to {{ title }}!
  </h1>
  <img width="300" alt="Angular Logo" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNTAgMjUwIj4KICAgIDxwYXRoIGZpbGw9IiNERDAwMzEiIGQ9Ik0xMjUgMzBMMzEuOSA2My4ybDE0LjIgMTIzLjFMMTI1IDIzMGw3OC45LTQzLjcgMTQuMi0xMjMuMXoiIC8+CiAgICA8cGF0aCBmaWxsPSIjQzMwMDJGIiBkPSJNMTI1IDMwdjIyLjItLjFWMjMwbDc4LjktNDMuNyAxNC4yLTEyMy4xTDEyNSAzMHoiIC8+CiAgICA8cGF0aCAgZmlsbD0iI0ZGRkZGRiIgZD0iTTEyNSA1Mi4xTDY2LjggMTgyLjZoMjEuN2wxMS43LTI5LjJoNDkuNGwxMS43IDI5LjJIMTgzTDEyNSA1Mi4xem0xNyA4My4zaC0zNGwxNy00MC45IDE3IDQwLjl6IiAvPgogIDwvc3ZnPg==">
</div>
<h2>Here are some links to help you start: </h2>
<ul>
  <ngx-infinitegrid #ig
    [loading]="loading"
    [options]="{isConstantSize:true}"
    [layoutOptions]="{margin: 5, align: 'center'}"
    [items]="items" (append)="onAppend($event)" (layoutComplete)="onLayoutComplete($event)" (imageError)="onImageError($event)">
    <div class="loading" #loading>LOADING?</div>
    <div class="item" *ngFor ="let item of ig.visibleItems; trackBy: trackBy;">
      <div class="thumbnail">
        <img [src]="'https://naver.github.io/egjs-infinitegrid/assets/image/' + (item.no % 59) + '.jpg'"/>
      </div>
      <div class="info">
        egjs {{item.no}}
      </div>
    </div>
  </ngx-infinitegrid>
</ul>
