// packages/react-infinitegrid/src/App.tsx
import React from 'react';
import './App.css';
import { GridLayout } from './react-infinitegrid';

class Item extends React.Component<{
  groupKey: any,
  num: number,
  onClick: any,
}> {
  render() {
    const no = this.props.num;
    const text = `egjs ${no}`;

    return (<div className="item" onClick={this.props.onClick}>
      <div className="thumbnail">
        <img src={`https://naver.github.io/egjs-infinitegrid/assets/image/${no % 59}.jpg`} />
      </div>
      <div className="info">
        {text}
      </div>
    </div>);
  }
}

class App extends React.Component<{}, {
  list: any[],
}> {
  public start = 0;
  constructor(prop) {
    super(prop);
    this.state = {
      list: [
        ...this.loadItems("1", 10).slice(1),
        ...this.loadItems("2", 10),
      ],
    };
  }
  loadItems(groupKey, num) {
    const items = [];
    const start = this.start || 0;

    for (let i = 0; i < num; ++i) {
      items.push(<Item groupKey={groupKey} num={start + i} key={start + i}
        onClick={(itemKey => (e => this.remove(itemKey)))(start + i)} />);
    }
    this.start += num;
    return items;
  }
  remove(itemKey) {
    const list = this.state.list.slice();
    const index = list.map(component => parseFloat(component.key)).indexOf(itemKey);

    list.splice(index, 1);
    this.setState({ list });
  }
  onAppend = ({ currentTarget, groupKey, startLoading }) => {
    if (currentTarget.isLoading()) {
      return;
    }
    startLoading();
    const list = this.state.list;
    const items = this.loadItems(parseFloat(groupKey || 0) + 1, 5);

    this.setState({ list: list.concat(items) });
  }
  onLayoutComplete = ({ isAppend, isLayout, endLoading, fromCache }) => {
    !isLayout && endLoading();
  }
  onImageError = ({ totalIndex }) => {
    this.state.list.splice(totalIndex, 1);
    this.setState({ list: this.state.list });
  }
  render() {
    const { list } = this.state;

    return (
      <GridLayout
        ref={e => {
          (window as any).a = e;
        }}
        options = {{
          transitionDuration: 0,
          isConstantSize: false,
        }}
        layoutOptions={{
          margin: 10,
          align: "center",
        }}
        onAppend={this.onAppend}
        onLayoutComplete={this.onLayoutComplete}
        onImageError={this.onImageError}
        useFirstRender={true}
        loading={<div className="loading" style={{textAlign: "center", height: "100px", backgroundColor: "#f55", position: "absolute"}}>LOADING</div>}
        // status={status}
      >
        {list}
      </GridLayout>
    );
  }
}


export default App;

// packages/svelte-infinitegrid/src/demo/App.svelte
<script lang="ts">
  import InfinitGrid from "../index";
  let ig;
  let items = [];
  let loading;

  function loadItems(groupKey, nextKey, itemCount) {
    const nextItems = [];

    for (let i = 0; i < itemCount; ++i) {
      nextItems.push({ groupKey, key: nextKey + i });
    }
    return nextItems;
  }
  function onAppend({ detail: { groupKey, startLoading } }) {
    if (ig.isProcessing()) {
      return;
    }
    startLoading();
    const nextGroupKey = (parseFloat(groupKey) || 0) + 1;
    const nextKey = items.length;

    items = [...items, ...loadItems(nextGroupKey, nextKey, 10)];
  }
  function onLayoutComplete({ detail: { isLayout, endLoading } }) {
    !isLayout && endLoading();
  }
</script>

<style>
  .item {
    width: 250px;
    opacity: 1;
  }
  .item .thumbnail {
    max-height: 300px;
    overflow: hidden;
    border-radius: 8px;
  }
  .item .thumbnail img {
    width: 100%;
    border-radius: 8px;
  }
  .item .info {
    margin-top: 10px;
    font-weight: bold;
    color: #777;
  }
  .item.animate {
    transition: opacity ease 1s;
    transition-delay: 0.2s;
    opacity: 1;
  }
  .loading {
    position: absolute;
    width: 100%;
    height: 50px;
    line-height: 50px;
    text-align: center;
    font-weight: bold;
  }
</style>

<InfinitGrid
  bind:this={ig}
  {items}
  {loading}
  itemBy={item => item.key}
  groupBy={item => item.groupKey}
  options={{ isConstantSize: true, transitionDuration: 0.2 }}
  layoutOptions={{ margin: 10, align: 'center' }}
  on:append={onAppend}
  on:layoutComplete={onLayoutComplete}
  let:visibleItems>
  {#each visibleItems as item (item.key)}
    <div class="item">
      <div class="thumbnail">
        <img
          src={`https://naver.github.io/egjs-infinitegrid/assets/image/${(item.key % 59) + 1}.jpg`}
          alt="egjs" />
      </div>
      <div class="info">{`egjs ${item.key}`}</div>
    </div>
  {/each}
  <div bind:this={loading} slot="loading">Loading</div>
</InfinitGrid>
